catta/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.iniciar_sesion, name='iniciar_sesion'),
    url(r'^admin/', admin.site.urls),
    url(r'^turnos/', include('turnos.urls')),
    url(r'^gestion/', include('gestion.urls')),
    url(r'^personas/', include('personas.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^ayuda_externa', views.ayuda_externa, name='ayuda_externa'),
    # Cuenta nueva.
    url(r'^cuenta/$', views.cuenta, name='cuenta'),
    # Vista del cliente.
    url(r'^ayuda_cliente/', views.ayuda_cliente, name='ayuda_cliente'),
    url(r'^cliente/$', views.cliente, name='cliente'),
    url(r'^nuevo_empleado/$', views.nuevo_empleado, name='nuevo_empleado'),  # TODO Ver si esto realmente es necesario.
    # Vista del empleado.
    url(r'^empleado/$', views.empleado, name='empleado'),
    url(r'^empleado/(\d+)/$', views.empleado, name='empleado'),
    url(r'^ayuda_empleado/', views.ayuda_empleado, name='ayuda_empleado'),
    # Listados de la vista del empleado.
    url(r'^empleado_lista_clientes/$', views.empleado_lista_clientes, name='empleado_lista_clientes'),
    url(r'^empleado_lista_servicios$', views.empleado_lista_servicios, name='empleado_lista_servicios'),
    url(r'^empleado_lista_insumos$', views.empleado_lista_insumos, name='empleado_lista_insumos'),
    url(r'^empleado_lista_turnos/$', views.empleado_lista_turnos, name='empleado_lista_turnos'),
    # Vista de la dueña.
    url(r'^duenio/$', views.duenio, name='duenio'),
    url(r'^ayuda_duenio/', views.ayuda_duenio, name='ayuda_duenio'),
    # Listados de la vista de la dueña.
    url(r'^modificar_stock_duenio/(\d+)/$', views.modificar_stock_duenio, name='modificar_stock_duenio'),
    url(r'^duenio_lista_empleados/$', views.duenio_lista_empleados, name='duenio_lista_empleados'),
    url(r'^duenio_lista_clientes/$', views.duenio_lista_clientes, name='duenio_lista_clientes'),
    url(r'^duenio_lista_servicios$', views.duenio_lista_servicios, name='duenio_lista_servicios'),
    url(r'^duenio_lista_insumos$', views.duenio_lista_insumos, name='duenio_lista_insumos'),
    url(r'^duenio_lista_turnos/$', views.duenio_lista_turnos, name='duenio_lista_turnos'),
    url(r'^duenio_lista_turno_creado_fijo/(\d+)/$', views.duenio_lista_turno_creado_fijo, name='duenio_lista_turno_creado_fijo'),
    url(r'^duenio_lista_comisiones/$', views.duenio_lista_comisiones, name='duenio_lista_comisiones'),
    url(r'^modificarComision/(\d+)/$', views.modificarComision, name='modificarComision'),
    url(r'^duenio_agenda/$', views.agenda_duenio, name='agenda_duenio'),
    url(r'^cliente_agenda/$', views.agenda_cliente, name='agenda_cliente'),
    url(r'^empleado_agenda/$', views.agenda_empleado, name='agenda_empleado'),
    url(r'^crear_turno/$', views.crear_turno_cliente, name='crear_turno'),
    url(r'^cliente_lista_servicios$', views.cliente_lista_servicios, name='cliente_lista_servicios'),
    url(r'^modificarComision/(\d+)/$', views.modificarComision, name='modificarComision'),
    url(r'^cliente_lista_turnos/$', views.cliente_lista_turnos, name='cliente_lista_turnos'),
    url(r'^restringido/$', views.restringido, name='restringido'),
    url(r'^ingreso_neto/$', views.ingreso_neto, name='ingreso_neto'),
    url(r'^servicios_mas_solicitados/$', views.servicios_mas_solicitados, name='servicios_mas_solicitados'),
    url(r'^mes_mayor_trabajo/$', views.mes_mayor_trabajo, name='mes_mayor_trabajo'),
    url(r'^dia_mayor_trabajo/$', views.dia_mayor_trabajo, name='dia_mayor_trabajo'),
    url(r'^dias_mayor_creaciones_turnos/$', views.dias_mayor_creaciones_turnos, name='dias_mayor_creaciones_turnos'),
    url(r'^clientes_con_mas_ausencias/$', views.clientes_con_mas_ausencias, name='clientes_con_mas_ausencias'),
    url(r'^empleados_mas_solicitados/$', views.empleados_mas_solicitados, name='empleados_mas_solicitados'),
    url(r'^horarios_mas_solicitados/$', views.horarios_mas_solicitados, name='horarios_mas_solicitados'),
    url(r'^servicios_mas_solicitados/$', views.servicios_mas_solicitados, name='servicios_mas_solicitados'),
    url(r'^empleados_mas_solicitados/$', views.empleados_mas_solicitados, name='empleados_mas_solicitados'),
    # Reportes
    url(r'^empleados_mas_solicitados_pdf/', views.EmpleadosMasSolicitadosPDF.as_view(), name="empleados_mas_solicitados_pdf"),
    url(r'^empleados_mas_solicitados_excel/', views.empleados_mas_solicitados_excel, name="empleados_mas_solicitados_excel"),
    # Cerrar Sesión.
    url(r'^$', views.cerrar_sesion, name='cerrar_sesion')

]

personas/models.py
from django.contrib.auth.models import AbstractUser
from gestion.models import *
from datetime import datetime
from _datetime import date


class Rol(models.Model):
    class Meta:
        abstract = True

    def __str__(self):
        try:
            return '{} {}'.format(self.persona.nombre, self.persona.apellido)
        except AttributeError:
            return 'Rol no asignado'

class Cliente(Rol):
    email = models.EmailField(max_length=100, default='test@test.com')
    # historial = []  # LISTA DE TURNOS (HISTORIAL)


class Empleado(Rol):
    porc_comision = models.PositiveIntegerField()
    sector = models.ForeignKey(Sector, null=True, blank=True)
    # agenda = []  # LISTA DE TURNOS (AGENDA)

    def __str__(self):
        return "{} {} {}".format(self.persona.nombre, self.persona.apellido, self.sector)

    def get_pago(self, costo):
        comision = self.porc_comision
        pago = (costo*comision)/100
        return pago

class Duenia(Rol):
    pass

    
class Usuario(AbstractUser, Rol):

    def get_vista(self):
        try:
            p = self.persona
            if p.duenia is not None:
                return 'duenio'
            elif p.empleado is not None:
                return 'empleado'
            elif p.cliente:
                return 'cliente'
        except models.ObjectDoesNotExist:
            pass
        return 'admin:index'


class Persona(models.Model):
    FILTROS = {
        "dni": ["dni__icontains"],
        "nombre": ["nombre__icontains"],
        "apellido": ["apellido__icontains"],
        "localidad": ["localidad__icontains"]
    }
    dni = models.PositiveIntegerField(primary_key=True)
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    direccion = models.CharField(max_length=100, null=True)
    telefono = models.PositiveIntegerField(null=True)
    localidad = models.CharField(max_length=100, null=True)
    cliente = models.OneToOneField(Cliente, null=True, blank=True)
    empleado = models.OneToOneField(Empleado, null=True, blank=True)
    duenia = models.OneToOneField(Duenia, null=True, blank=True)
    usuario = models.OneToOneField(Usuario, null=True, blank=True)

    def __str__(self):
        return "{} {} ".format(self.nombre, self.apellido)

    def get_rol_url(self):
        if self.cliente:
            rol = 'cliente'
        if self.empleado:
            rol = 'empleado'
        if self.duenia:
            rol = 'duenio'
        return rol


class Comision(models.Model):
    FILTROS = {
        "empleadoN": ["turno__empleado__persona__nombre__icontains"],
        "empleadoA": [ "turno__empleado__persona__apellido__icontains"],
        "fechaI": ["fecha_liquidacion__gte"],
        "fechaF": ["fecha_liquidacion__lte"],
        "montoD": ["monto__gte"],
        "montoH": ["monto__lte"],
        "servicio": ["turno__servicios__nombre__icontains", "turno__promociones__nombre__icontains",
                     "turno__promociones__servicios__nombre__icontains"]
    }

    fecha_liquidacion = models.DateField(default=datetime.now)
    monto = models.FloatField(null=True)

turnos/models.py
from personas.models import *
from django.utils import timezone
from django.db.models import Q, Sum, F
from django.conf import settings
from django.utils import timezone
import  enum
from datetime import date, time, timedelta, datetime

class TurnoBaseManager(models.Manager):
    def get_queryset(self):
        qs = super().get_queryset().annotate(servicio_modulos=Sum("servicios__duracion"))
        qs = qs.annotate(promocion_modulos=Sum("promociones__servicios__duracion"))
        return qs

class TurnoQuerySet(models.QuerySet):
    def en_dia(self, date):
        return self.filter(fecha__date = date)

    def en_estado(self, estado):
        return self.filter(Turno.FILTROS["estado"][estado])

TurnoManager = TurnoBaseManager.from_queryset(TurnoQuerySet)

def crear_rango(turno):
    r = []
    base = turno[0]
    while base <= turno[1]:
        r.append(base)
        base = (datetime.combine(date.today(), base) + settings.MODULO).time()
    return r

class Turno(models.Model):
    CONFIRMADO = 2
    CANCELADO = 0
    SIN_CONFIRMAR = 1
    REALIZADO = 3
    ESTADOS = [
        (CANCELADO, "Cancelado"),
        (SIN_CONFIRMAR, "Sin Confirmar"),
        (CONFIRMADO, "Confirmado"),
        (REALIZADO, "Realizado")
    ]
    FILTROS = {
        "fechaI": ["fecha__date__gte"],
        "fechaF": ["fecha__date__lte"],
        "fechaCI": ["fecha_creacion__gte"],
        "fechaCF": ["fecha_creacion__lte"],
        "sector": ["empleado__sector__icontains"],
        "clienteN": [ "cliente__persona__nombre__icontains"],
        "clienteA": ["cliente__persona__apellido__icontains"],
        "empleadoN": ["empleado__persona__nombre__icontains"],
        "empleadoA": [ "empleado__persona__apellido__icontains"],
        "servicio": [ "servicios__nombre__icontains", "promociones__nombre__icontains", "promociones__servicios__nombre__icontains" ],
        "estado": {
            CANCELADO: Q(fecha_cancelacion__isnull = False),
            REALIZADO: Q(fecha_realizacion__isnull = False),
            CONFIRMADO: Q(fecha_confirmacion__isnull = False) & Q(fecha_realizacion__isnull = True) & Q(fecha_cancelacion__isnull = True),
            SIN_CONFIRMAR: Q(fecha_confirmacion__isnull = True) & Q(fecha_realizacion__isnull = True) & Q(fecha_cancelacion__isnull = True)
        }
    }
    #fecha se deja como esta pero a su vez se divide en dos atributos mas fecha sola y hora,
    #fecha creacion se le quita la hora. que dia se sacan mas turnos
    fecha = models.DateTimeField()  # Fecha en la que se realizara el turno.
    dia = models.DateField(default=date.today)
    hora = models.TimeField(default=timezone.now)
    # TIEMPO_MAX_CONFIRMACION = fecha - timedelta(days=2)  # Tiempo maximo de confirmación
    fecha_creacion = models.DateField(default=date.today)
    fecha_confirmacion = models.DateTimeField(null=True, blank=True)
    fecha_realizacion = models.DateTimeField(null=True, blank=True)
    fecha_cancelacion = models.DateTimeField(null=True, blank=True)
    servicios = models.ManyToManyField(ServicioBasico, blank=True, related_name="turnos")
    promociones = models.ManyToManyField(Promocion, blank=True, related_name="turnos")
    empleado = models.ForeignKey(Empleado)
    cliente = models.ForeignKey(Cliente)
    objects = TurnoManager()
    comision = models.ForeignKey(Comision, null=True, blank=True)

    def __str__(self):
        return "{}".format(self.fecha)

    @classmethod
    def posibles_turnos(cls, fecha, servicios=None, promociones=None, usuario=None):
        delta = timedelta(minutes=0)
        turnos = cls.objects.en_dia(fecha).en_estado(not Turno.CANCELADO)
        if usuario is not None:
            turnos = turnos.filter(empleado=usuario)
        if servicios is not None:
            for servicio in servicios:
                delta += ServicioBasico.objects.all().filter(id=servicio).first().get_duracion()
        if promociones is not None:
            for promocion in promociones:
                delta += Promocion.objects.all().filter(id=promocion).first().get_duracion()
        # Crea el set con todos los horarios del día.
        rango = set(crear_rango(settings.MAÑANA) + crear_rango(settings.TARDE))
        # Si el día elegido es hoy, elimina los horarios anteriores a la hora actual.
        if fecha == datetime.today().date():
            for r in reversed(sorted(rango)):
                if r <= datetime.today().time():
                    rango.remove(r)
        # Saca del set de horarios los que sobrepasan el tamaño del turno a crear.
        rango = rango.difference(crear_rango((
            (datetime.combine(date.today(), settings.TARDE[1]) - delta).time(),
            settings.TARDE[1])))
        for t in turnos:
            r = crear_rango((t.fecha.time(), (t.fecha + t.duracion()).time()))
            rango = rango.difference(r)

        return sorted(rango)

    def duracion(self):
        return ((self.servicio_modulos or 0) +
                (self.promocion_modulos or 0)) * settings.MODULO

    def get_cliente(self):
        return str(self.cliente)

    def get_empleado(self):
        return str(self.empleado)

    def get_servicios(self):
        servicios = self.servicios.all()
        nombres = ""
        for servicio in servicios:
            nombres += servicio.get_nombre()
        return str(nombres)

    def get_promociones(self):
        promociones = self.promociones.all()
        nombres = ""
        for promocion in promociones:
            nombres += promocion.get_nombre()
        return str(nombres)

    def get_duracion(self):
        servicios = self.servicios.all()
        duracion = self.fecha

        for servicio in servicios:
            duracion += servicio.get_duracion()
        return duracion

    def get_proximo_turno(self, turno):

        fecha_turno = turno.fecha
        fecha_1 = fecha_turno.replace(hour=00, minute=00, second=00)
        fecha_2 = fecha_turno.replace(hour=20, minute=00, second=00)

        empleado = turno.empleado

        turnos = Turno.objects.filter(empleado=empleado, fecha__range=[fecha_1, fecha_2]).order_by('fecha')

        turno_sig = None

        if turnos != None:
            for turno_siguiente in turnos:
                fecha = turno_siguiente.fecha
                if fecha_turno < fecha:
                    turno_sig = turno_siguiente
                    return turno_sig

        return turno_sig

    def estado(self):
        if self.fecha_realizacion is not None:
            return "Realizado"
        else:
            if self.fecha_cancelacion is not None :
                return "Cancelado"
            else:
                if self.fecha_confirmacion is not None:
                    return "Confirmado"
                else:
                    return "Sin Confirmar"

    def cancelar_turno(self):
        self.fecha_cancelacion = datetime.now()

    def realizar_turno(self):
        self.fecha_realizacion = datetime.now()

    def confirmar_turno(self):
        self.fecha_confirmacion = datetime.now()

    def get_costo(self):
        costo = 0
        for servicio in  self.servicios.all():
            costo += servicio.precio
        for promociones in self.promociones.all():
            costo += promociones.precio

        return costo

    def get_ganancia_neta(self):
        ganancia = self.get_costo()
        ganancia = ganancia - ((self.empleado.porc_comision * ganancia)/100)
        return ganancia

    def get_perdida_neta(self):
        ganancia = self.get_costo() - self.get_ganancia_neta()
        return ganancia

    def get_fecha(self):
        formato = "%d-%m-%y %I"
        return self.fecha.strftime(formato)

class TurnoFijo(Turno):
    MARTES ='Martes'
    MIERCOLES ='Miercoles'
    JUEVES ='Jueves'
    VIERNES ='Viernes'
    SABADO ='Sabado'
    DIA = [
        (MARTES, 'Martes'),
        (MIERCOLES, 'Miercoles'),
        (JUEVES, 'Jueves'),
        (VIERNES, 'Viernes'),
        (SABADO, 'Sabado')
    ]
    # ATRIBUTO DIA (EJEMPLO: Turno fijo los JUEVES) PUEDE SER ENUMERADO
    #turno_siguiente = models.OneToOneField('self',null=True, blank=True,default=self.calcular_turno_siguiente())
    turno_siguiente = models.OneToOneField('self', null=True)
    fecha_fin = models.DateTimeField()
    #dia = models.CharField(max_length=9, choices=DIA, default='Martes')

    def calcular_turno_siguiente(self,f):
        print(f)
        fecha_nueva = f + timedelta(days=7)
        #fecha_1 = self.get_duracion()
        #formato = "%d-%m-%y"
        #fecha_1 = fecha_nueva
        #fecha_2 = fecha_nueva
        fecha_1 = fecha_nueva.replace(hour= 00, minute = 00, second = 00)
        fecha_2 = fecha_nueva.replace(hour = 20, minute = 00, second = 00)
        existe = Turno.objects.filter(empleado=self.empleado, fecha=fecha_nueva).exists()
        #existen = Turno.objects.filter(empleado=self.empleado)
        existen = Turno.objects.filter(empleado=self.empleado, fecha__range=[fecha_1, fecha_2])
        for e in existen:
            print ("hay existen")
            print(e)
            if e.get_fecha() == fecha_2:
                if (e.fecha < fecha_nueva and e.get_duracion() > fecha_nueva) or (fecha_nueva < e.fecha and e.fecha < self.get_duracion):
                    existe = True
                    break
        print(existe)
        if(self.fecha_fin > fecha_nueva):
            if (not existe):
                t = TurnoFijo()
                t.empleado = self.empleado
                t.fecha = fecha_nueva
                t.fecha_fin = self.fecha_fin
                t.cliente = self.cliente
                t.save()
                serv = self.servicios.all()
                for s in serv:
                    t.servicios.add(s)
                prom = self.promociones.all()
                for p in prom:
                    t.promociones.add(p)
                t.save()
                self.turno_siguiente = t
                print(self.turno_siguiente.fecha)
                t.calcular_turno_siguiente(t.fecha)

personas/templates/duenio/base_duenio.html
{% extends "base/base.html" %}

{% load staticfiles %}

{% block barra %}
    <div id="hornav" class="container no-padding">
        <div class="row">
            <div class="col-md-12 no-padding">
                <div class="visible-lg">
                    <ul id="hornavmenu" class="nav navbar-nav navbar-fixed-top" style="height: 60px">
                        <li class="navbar-left">
                            <a href="{% url 'duenio' %}" class="fa-home">Principal</a>
                        </li>
                        <li class="navbar-right">
                            <span class="fa-user-md">Cuenta</span>
                            <ul>
                                <li class="">
                                    <a href="{% url 'cerrar_sesion' %}">Cerrar Sesión</a>
                                </li>
                            </ul>
                        </li>
                        <li class="navbar-left">
                            <a href="{% url 'duenio_lista_empleados' %}" role="button" onclick="goto_link ('/duenio/duenio_lista_empleados/')">Empleados</a>
                        </li>
                        <li class="navbar-left">
                            <a href="{% url 'duenio_lista_clientes' %}" role="button" onclick="goto_link ('/duenio/duenio_lista_clientes/')">Clientes</a>
                        </li>
                        <li class="navbar-left">
                            <a href="{% url 'duenio_lista_servicios' %}" role="button" onclick="goto_link ('/duenio/duenio_lista_servicios/')">Servicios</a>
                        </li>
                        <li class="navbar-left">
                            <a href="{% url 'duenio_lista_insumos' %}" role="button" onclick="goto_link ('/duenio/duenio_lista_insumos/')">Insumos</a>
                        </li>
                        <li class="navbar-left">
                            <script> 
                                n1 = new Date();
                                n1.setDate(n1.getDate() -7)
                                yI = n1.getFullYear();
                                mI = n1.getMonth() + 1;
                                dI = n1.getDate();
                                n2 =  new Date();
                                yF = n2.getFullYear();
                                mF = n2.getMonth() + 1;
                                dF = n2.getDate();
                                fechaFn = yF + "-" + mF + "-" + dF;
                                fechaIn = yI + "-" + mI + "-" + dI;
                                cadena = "<a href=\"{% url 'duenio_lista_turnos' %}?clienteN=&clienteA=&empleadoN=&empleadoA=&fechaI=" + fechaIn + "&fechaF=" + fechaFn + "&servicio=\" role=\"button\" onclick=\"goto_link ('/duenio/duenio_lista_turnos/')\">Turnos</a>"
                                document.write(cadena); 
                            </script>
                        </li>
                        <li class="navbar-left">
                            <a href="{% url 'duenio_lista_comisiones' %}" role="button" onclick="goto_link ('/duenio/duenio_lista_comisiones/')">Comisiones</a>
                        </li>
                        <li class="navbar-left">
                            <span>Reportes</span>
                            <ul>
                                <li class="">
                                    <script> 
                                        n1 = new Date();
                                        n1.setDate(n1.getDate() -7)
                                        yI = n1.getFullYear();
                                        mI = n1.getMonth() + 1;
                                        dI = n1.getDate();
                                        n2 =  new Date();
                                        yF = n2.getFullYear();
                                        mF = n2.getMonth() + 1;
                                        dF = n2.getDate();
                                        fechaFn = yF + "-" + mF + "-" + dF;
                                        fechaIn = yI + "-" + mI + "-" + dI;
                                        cadena = "<a href=\"{% url 'ingreso_neto' %}?clienteN=&clienteA=&empleadoN=&empleadoA=&fechaI=" + fechaIn + "&fechaF=" + fechaFn + "&servicio=\">Ingreso Neto</a>"
                                        document.write(cadena); 
                                    </script>
                                </li>                                
                                <li class="">
                                    <a href="{% url 'servicios_mas_solicitados' %}">Servicios/Promociones más Solicitados</a>
                                </li>
                                <li class="">
                                    <a href="{% url 'mes_mayor_trabajo' %}">Mes con Mayor Trabajo</a>
                                </li>
                                <li class="">
                                    <a href="{% url 'dia_mayor_trabajo' %}">Días con Mayor Trabajo</a>
                                </li>
                                <li class="">
                                    <a href="{% url 'dias_mayor_creaciones_turnos' %}">Días con mayor creaciones de turnos</a>
                                </li>
                                <li class="">
                                    <a href="{% url 'clientes_con_mas_ausencias' %}">Clientes con más ausencias</a>
                                </li>
                                <li class="">
                                    <a href="{% url 'empleados_mas_solicitados' %}">Empleados Más Solicitados</a>
                                </li>
                                <li class="">
                                    <a href="{% url 'horarios_mas_solicitados' %}">Horarios Más Solicitados</a>
                                </li>
                            </ul>
                        </li>
                        <!-- AGENDA !-->
                        <li class="navbar-right">
                            <a href="{% url 'agenda_duenio' %}" role="button" onclick="goto_link ('/duenio/agenda/')"><i class="fa fa-calendar-o"></i></a>
                        </li>
                        <li class="navbar-right" >
                            <a href="{%url 'ayuda_duenio' %}" target="_blank" role="button">AYUDA</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block borde_arriba %}
<div id="content-top-border" class="container"></div>
{% endblock %}

{% block borde_abajo %}
<div id="content-bottom-border" class="container"></div>
{% endblock %}

{% block scripts %}
    {{ block.super }}

    <script>
        $(function() {
            $(".filtro").on("focusout", function(e) {
                $(e.target).parent("form").submit();
            })
        });
    </script>
    <script>
        $(myFunction(){
            windows.open();
        });
    </script>
{% endblock %}

personas/templates/duenio/comisiones_duenio.html
{% extends 'duenio/base_duenio.html' %}

{% load staticfiles %}

{% block contenido %}
    <div class="container background-white" style="opacity: 0.95;">
        <div class="row margin-vert-30">
            <div class="col-md-12">
                {% csrf_token %}

                <h2><font color="Purple"><font face="arial"><center> Listado de Comisiones </center></font></font></h2>
                <form method="get" action="">
                    Empleado:
                    <input name="empleadoN" placeholder="Nombre" value="{{ f.empleadoN }}" class="filtro">
                    <input name="empleadoA" placeholder="Apellido" value="{{ f.empleadoA }}" class="filtro">
                    Desde:
                    <input name="fechaI" placeholder="Desde (aaaa-mm-dd)" value="{{ f.fechaI }}" class="datetimeinput">
                    Hasta:
                    <input name="fechaF" placeholder="Hasta (aaaa-mm-dd)" value="{{ f.fechaF }}" class="datetimeinput">
                    <br>
                    Servicio:
                    <input name="servicio" placeholder="Servicio" value="{{ f.servicio }}" class="filtro">
                    Entre
                    <input name="montoD" placeholder="Monto min" value="{{ f.montoD }}" class="filtro">
                    y
                    <input name="montoH" placeholder="Monto max" value="{{ f.montoH }}" class="filtro">

                    <button class="btn btn-violet pull-right" type="submit">Filtrar</button>
                </form>
                <table class="table table-striped">
                    <thread>
                        <tr>
                            <th>Empleado</th>
                            <th>Fecha</th>
                            <th>Turnos</th>
                            <th>Monto</th>
                        </tr>
                    </thread>
                    <tbody>
                        {% for comision in comisiones %}
                        <tr>
                            <td>{{comision.turno_set.first.empleado}}</td>
                            <td>{{comision.fecha_liquidacion}}</td>
                            <td>{% for turno in comision.turno_set.all %}
                                    <details>
                                        <summary> {{turno}} </summary>
                                        {% for servicio in turno.servicios.all %}
                                            <li><i>{{servicio}}</i>
                                        {% endfor %}
                                        {% for promocion in turno.promociones.all %}
                                            <details>
                                                <summary>{{promocion}}</summary>
                                                {% for servicio in promocion.servicios.all %}
                                                      <li><i>{{servicio}}</i>
                                                {% endfor %}
                                            </details>
                                        {% endfor %}
                                    </details>

                                {% endfor %}</td>
                            <td>{{comision.monto}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
</div>
{% endblock %}

{% block scripts %}
{{ block.super }}
<script>
    $(function() {
        $(".datetimeinput").datepicker();
    });
</script>
{% endblock%}

personas/templates/duenio/insumos_duenio.html
{% extends 'duenio/base_duenio.html' %}

{% load staticfiles %}

{% block contenido %}
    <div class="container background-white" style="opacity: 0.95;">
    <div class="row margin-vert-30">
        <div class="col-md-12">
            {% csrf_token %}

            <h2><font color="Purple"><font face="arial"><center> Listado de Insumos </center></font></font></h2>
            <form method="get" action="">
                <input name="nombre" placeholder="Nombre" value="{{ f.nombre }}" class="filtro">
                <input name="marca" placeholder="Marca" value="{{ f.marca }}" class="filtro">
                <button class="btn btn-violet pull-right" type="submit">Filtrar</button>
            </form>
            <table class="table table-striped">
                <thread>
                    <tr>
                        <th>Nombre</th>
                        <th>Marca</th>
                        <th>Contenido Neto</th>
                        <th>Unidad de Medida</th>
                        <th>Stock</th>
                        <th>Modificar Stock</th>
                    </tr>
                </thread>
                <tbody>
                    {% for insumo in insumos %}
                    <tr>
                        <td>{{insumo.nombre}}</td>
                        <td>{{insumo.marca}}</td>
                        <td>{{insumo.contenidoNeto}}</td>
                        <td>{{insumo.unidadDeMedida}}</td>
                        <td>{{insumo.stock}}</td>
                        <td><a href="{% url 'modificar_stock_duenio' insumo.id %}" button type="button" class="btn btn-warning">Modificar</button onclick="goto_link ('personas/modificar_stock_duenio/1/2/')"></a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}